name: Deno Test

on:
    push:
        branches:
            - main
        paths:
            - "deno.json" # Trigger only when deno.json changes

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2 # Fetch current and previous commits

            - name: Compare Versions
              id: version_check
              shell: bash
              run: |
                  # Fetch the previous version if deno.json existed in the last commit
                  PREVIOUS_VERSION=$(git show HEAD~1:deno.json 2>/dev/null | jq -r '.version' || echo "")

                  # Extract the current version from the deno.json file
                  CURRENT_VERSION=$(jq -r '.version' deno.json)

                  echo "Current version: $CURRENT_VERSION"
                  echo "Previous version: $PREVIOUS_VERSION"

                  # Compare the versions and set output accordingly
                  if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
                      echo "version_changed=true" >> $GITHUB_OUTPUT
                  else
                      echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Setup Deno
              if: steps.version_check.outputs.version_changed == 'true'
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Run Formatter
              if: steps.version_check.outputs.version_changed == 'true'
              run: deno fmt --check

            - name: Run Linter
              if: steps.version_check.outputs.version_changed == 'true'
              run: deno lint

            - name: Run Tests
              if: steps.version_check.outputs.version_changed == 'true'
              run: deno test --allow-net --allow-read -- ${{ secrets.TEST_PRIVATE_KEY }}
