name: Publish Package to JSR
on:
    workflow_run:
        workflows: ["Deno Test"]
        types: [completed]

jobs:
    publish:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Publish package
              run: npx jsr publish
