name: Publish Package to npm
on:
    workflow_run:
        workflows:
            - Run Deno Tests
        types:
            - completed
    workflow_dispatch:

jobs:
    publish:
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4 # Checkout the repository
            - uses: denoland/setup-deno@v2 # Set up Deno
              with:
                  deno-version: v2.x # Run with latest stable Deno
            - uses: actions/setup-node@v4 # Set up Node.js
              with:
                  node-version: "22.x" # Run with latest stable Node.js
                  registry-url: "https://registry.npmjs.org" # Use npm registry

            - name: Get version
              id: get_version
              run: |
                  VERSION=$(jq -r '.version' deno.json)
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Check tag
              if: ${{ github.event_name == 'workflow_dispatch' }}
              id: check-tag
              run: |
                  if [[ "${{ steps.get_version.outputs.version }}" == *-* ]]; then
                    echo "tag_exists=true" >> $GITHUB_OUTPUT
                    echo "Tag found, manual publishing allowed"
                  else
                    echo "Error: Manual publishing without a tag is not allowed" >&2
                    exit 1
                  fi

            - name: npm build
              run: deno run -A ./build/npm.ts ${{ steps.get_version.outputs.version }}

            - name: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: cd ./build/npm && npm publish --access public
